version: '3.8'

services:
  front-mqdesk:
    container_name: front-mqdesk
    # The official v2 Traefik docker image
    image: front-mqdesk:latest
    restart: always
    ports:
      # The HTTP port
      - '8010:3000'
    networks:
      - applications-network
    environment:
      - NEXT_PUBLIC_BACKEND_API_KEY=${NEXT_PUBLIC_BACKEND_API_KEY}
      - NEXT_PUBLIC_BACKEND_API_SECRET=${NEXT_PUBLIC_BACKEND_API_SECRET}
      - NEXT_PUBLIC_API_URI=${NEXT_PUBLIC_API_URI}
networks:
  applications-network:
    external: true
    name: applications-network
